# MCU name
MCU = RP2040

# Bootloader selection
BOOTLOADER = rp2040

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = no
UNICODE_ENABLE = no
BLUETOOTH_ENABLE = no
SLEEP_LED_ENABLE = no
SPLIT_KEYBOARD = no
LAYOUTS = split_3x5_3
LTO_ENABLE = yes
SRC += features/caps_word.c

UNICODE_ENABLE = yes
# UNICODEMAP_ENABLE = yes
