MCU = RP2040
BOOTLOADER = rp2040

EEPROM_DRIVER = wear_leveling
WEAR_LEVELING_DRIVER = rp2040_flash

CAPS_WORD_ENABLE = yes
COMMAND_ENABLE = no
BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = no
BLUETOOTH_ENABLE = no
SLEEP_LED_ENABLE = no
SPLIT_KEYBOARD = no
LAYOUTS = ortho_4x10
LTO_ENABLE = yes

UNICODE_ENABLE = yes
# UNICODEMAP_ENABLE = yes
